### ISSUE TITLE
Deployed but

### ISSUE THREAD

**Issue by ingydotnet** [nebulous/nebulous.github.io#1]
I deployed the content to http://jemplate.net but I just copied the contents of your jemplate.net subdir into the gh-pages branch of ingydotnet/www.jemplate.net

I'd like to get a master branch that generates a gh-pages branch. Hmm. I'll just make you a collaborator and you can redo the master and gh-pages branches. I tagged the old ones, so go ahead and replace them.

**Comment by nebulous** [comment]
I'm not sure I follow. Do you want to keep the jemplate site in the ingydotnet/www.jemplate.net repo, or would you like to add a gh-pages branch to the ingydotnet/jemplate repo? Happy to help whatever the circumstance, but don't want to add confusion since I have collaborator access to both repositories.

**Comment by ingydotnet** [comment]
Sorry. I was a bit distracted yesterday. I just did this myself. Basically I:
- Forked your repo
- filter-branch'd your master `jemplate.net` on top of your gh-pages
- Fetched master and gh-pages from the fork into www.jemplate.net and made those replace the old master and gh-pages.
- Force pushed the new branches

So now your history is preserved and live. You still have push, and should do all new stuff directly to `ingydotnet/www.jemplate.net`. I think we can remove all the stuff in master except the readme.

Let's close this now.

Thanks a million. See you on #jemplate.
